apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name:  binary_scan

jobs:
  scan:
    steps:
      - name: Initiate execution plan
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:59cf7112b01c107036fb32dbb272402525a50ba0
        id: plan
        with:
          entrypoint: assets-plugin-chain-utils
          args: configure
        env:
          INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_RUN_ID: ${{ cloudbees.run_id }}
          INPUT_PLUGIN_LIST: 'trivy,findsecbugs,syft,grype'

      - name: Workflow Artifact Inventory
        if: ${{ steps.plan.outputs.wfartifact-master == 'true' }}
        env:
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_WF_ARTIFACT_TOKEN: ${{ steps.plan.outputs.wf_artifact_token }}
          INPUT_COMPONENT_ID: ${{ steps.plan.outputs.wf_artifact_component_id }}
          EXECUTION_ROLE: "MASTER"
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-cbp-workflow-artifacts:8382e6e9950699b950b709f0bf18508b8b344f3d
        run: /app/plugin-cbp-workflow-artifacts -mode single

      - name: Workflow Artifact Metadata
        if: ${{ steps.plan.outputs.wfartifact-decorator == 'true' }}
        env:
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_WF_ARTIFACT_TOKEN: ${{ steps.plan.outputs.wf_artifact_token }}
          INPUT_COMPONENT_ID: ${{ steps.plan.outputs.wf_artifact_component_id }}
          EXECUTION_ROLE: "DECORATOR"
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-cbp-workflow-artifacts:8382e6e9950699b950b709f0bf18508b8b344f3d
        run: /app/plugin-cbp-workflow-artifacts -mode single

      - name: Trivy Scanner
        if: ${{ steps.plan.outputs.trivy == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-trivy-scanner:e181a913cf03f17783fd822f6a14c0ec9d8bbd7d
        continue-on-error: true
        run: /app/plugin-trivy-scanner -mode single

      - name: FindSecBugs Scanner
        if: ${{ steps.plan.outputs.findsecbugs == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-findsecbugs-scanner:932f444a36c0dc3fc6e9a1d27b831169f41f3144
        continue-on-error: true
        run: /app/plugin-findsecbugs -mode single

      - name: Syft SBOM analyser
        if: ${{ steps.plan.outputs.syft == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-syft-sbom:e2c024c27b48510a7943a072d77f9e1d2fe22510
        continue-on-error: true
        run: /app/plugin-syftbom-analyser -mode single

      - name: Grype Scanner
        if: ${{ steps.plan.outputs.grype == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-grype-scanner:09c7f12ff47ccf11594aa312a2b0389256ee3951
        continue-on-error: true
        run: /app/plugin-grype-scanner -mode single

      - name: Complete execution plan
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:59cf7112b01c107036fb32dbb272402525a50ba0
        id: process-outputs
        with:
          entrypoint: assets-plugin-chain-utils
          args: process-outputs
        env:
          INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_RUN_ID: ${{ cloudbees.run_id }}