apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name:  binary_scan

jobs:
  scan:
    steps:
      - name: Initiate execution plan
        uses: https://github.com/cloudbees-io/asset-chain-utils/start-chain@v1
        id: plan

      # Login to AWS if region and role arn are provided to pull private images from ECR
      - name: Login to AWS
        if: ${{ steps.plan.outputs.ecr_region_name != 'false' && steps.plan.outputs.ecr_role_arn != 'false' }}
        uses: https://github.com/cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: ${{ steps.plan.outputs.ecr_region_name }}
          role-to-assume: ${{ steps.plan.outputs.ecr_role_arn }}
          role-duration-seconds: "3600"

      - name: ECR Artifact Inventory
        if: ${{ steps.plan.outputs.ecr-inventory == 'true' }}
        env:
          INPUT_AWS_REGION: ${{ steps.plan.outputs.ecr_region_name }}
          EXECUTION_ROLE: "MASTER"
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-aws-ecr:1b58cd9a75aaf586d2d377bc09f8e92e65ef66ac
        run: /app/plugin-aws-ecr -mode single

      - name: ECR Artifact Metadata
        if: ${{ steps.plan.outputs.ecr-metadata == 'true' }}
        env:
          INPUT_AWS_REGION: ${{ steps.plan.outputs.ecr_region_name }}
          EXECUTION_ROLE: "DECORATOR"
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-aws-ecr:1b58cd9a75aaf586d2d377bc09f8e92e65ef66ac
        run: /app/plugin-aws-ecr -mode single

      - name: Workflow Artifact Inventory
        if: ${{ steps.plan.outputs.wfartifact-inventory == 'true' }}
        env:
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_WF_ARTIFACT_TOKEN: ${{ steps.plan.outputs.wf_artifact_token }}
          INPUT_COMPONENT_ID: ${{ steps.plan.outputs.wf_artifact_component_id }}
          EXECUTION_ROLE: "MASTER"
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-cbp-workflow-artifacts:fdcc5aceb0adc0ea70cba5f3e5b94bfc0bc13750
        run: /app/plugin-cbp-workflow-artifacts -mode single

      - name: Workflow Artifact Metadata
        if: ${{ steps.plan.outputs.wfartifact-decorator == 'true' }}
        env:
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_WF_ARTIFACT_TOKEN: ${{ steps.plan.outputs.wf_artifact_token }}
          INPUT_COMPONENT_ID: ${{ steps.plan.outputs.wf_artifact_component_id }}
          EXECUTION_ROLE: "DECORATOR"
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-cbp-workflow-artifacts:fdcc5aceb0adc0ea70cba5f3e5b94bfc0bc13750
        run: /app/plugin-cbp-workflow-artifacts -mode single

      - name: Trivy Scanner
        if: ${{ steps.plan.outputs.trivy == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-trivy-scanner:91e1e9e794cb9c2bb69f44b41ab9c3ff5f765ca8
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-trivy-scanner -mode single

      - name: FindSecBugs Scanner
        if: ${{ steps.plan.outputs.findsecbugs == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-findsecbugs-scanner:d765e91c1af6d98626d5d6de10f8bd7c1909b9a4
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-findsecbugs -mode single

      - name: Syft SBOM analyser
        if: ${{ steps.plan.outputs.syft == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-syft-sbom:bf0c0eed8d7205c57e618a10afad78f74b6ed808
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-syftbom-analyser -mode single

      - name: Grype Scanner
        if: ${{ steps.plan.outputs.grype == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-grype-scanner:24c5c03b4793488b64cfb076262f28b81727cdf6
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-grype-scanner -mode single

      - name: Complete execution plan
        uses: https://github.com/cloudbees-io/asset-chain-utils/end-chain@v1
        id: process-outputs
