apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name:  scan

jobs:
  scan:
    steps:
      - name: Initiate execution plan
        uses: https://github.com/cloudbees-io/asset-chain-utils/start-chain@v1
        id: plan


      - name: Github Inventory
        if: ${{ steps.plan.outputs.github-inventory == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-github-inventory:e7444f9a1dad87482778356ec66dcd5f22e1e71e
        env:
          ACCOUNT_CREDENTIALS: ${{ steps.plan.outputs.account_credentials}}
        run: /app/plugin-git-master -mode single

      - name: Github Metadata
        if: ${{ steps.plan.outputs.github-decorator == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-github-metadata:532d1b6873dbbc40ab3e3726a8d929f8e4d02d99
        env:
          ACCOUNT_CREDENTIALS: ${{ steps.plan.outputs.account_credentials}}
        run: /app/plugin-git-decorator -mode single

      - name: Bitbucket Inventory
        if: ${{ steps.plan.outputs.bitbucket-inventory == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-bitbucket-server:eb81dba284f3a4fc1c5c60de0dd0c8946f8b4ae2
        env:
          ACCOUNT_CREDENTIALS: ${{ steps.plan.outputs.account_credentials}}
          EXECUTION_ROLE: "MASTER"
        run: /app/plugin-bitbucket -mode single

      - name: Bitbucket Metadata
        if: ${{ steps.plan.outputs.bitbucket-decorator == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-bitbucket-server:eb81dba284f3a4fc1c5c60de0dd0c8946f8b4ae2
        env:
          ACCOUNT_CREDENTIALS: ${{ steps.plan.outputs.account_credentials}}
          EXECUTION_ROLE: "DECORATOR"
        run: /app/plugin-bitbucket -mode single
        
      - name: Gerrit Inventory
        if: ${{ steps.plan.outputs.gerrit-inventory == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-gerrit:4f67b70bc378823d7583b4f53d56c552c943adfb
        env:
          ACCOUNT_CREDENTIALS: ${{ steps.plan.outputs.account_credentials}}
          EXECUTION_ROLE: "MASTER"
        run: /app/plugin-gerrit -mode single

      - name: Gerrit Metadata
        if: ${{ steps.plan.outputs.gerrit-decorator == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-gerrit:4f67b70bc378823d7583b4f53d56c552c943adfb
        env:
          ACCOUNT_CREDENTIALS: ${{ steps.plan.outputs.account_credentials}}
          EXECUTION_ROLE: "DECORATOR"
        run: /app/plugin-gerrit -mode single

      - name: GitLab Inventory
        if: ${{ steps.plan.outputs.gitlab-inventory == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-gitlab:0a0bdd22720e9f3334ef955a9f84aab36c116d4c
        env:
          ACCOUNT_CREDENTIALS: ${{ steps.plan.outputs.account_credentials}}
          EXECUTION_ROLE: "MASTER"
        run: /app/plugin-gitlab -mode single

      - name: GitLab Metadata
        if: ${{ steps.plan.outputs.gitlab-decorator == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-gitlab:0a0bdd22720e9f3334ef955a9f84aab36c116d4c
        env:
          ACCOUNT_CREDENTIALS: ${{ steps.plan.outputs.account_credentials}}
          EXECUTION_ROLE: "DECORATOR"
        run: /app/plugin-gitlab -mode single

      - name: SCC Scanner
        if: ${{ steps.plan.outputs.scc == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-scc-scanner:9393ab805bb706c829c471e1dfc8e6ee73541253
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-scc-scanner -mode single

      - name: GoSec Scanner
        if: ${{ steps.plan.outputs.gosec == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-gosec-scanner:eb064c4e8ba64a4516a6eb86db2dc76f13f20a53
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-gosec-scanner -mode single

      - name: Njs Scanner
        if: ${{ steps.plan.outputs.njsscan == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-njsscan-scanner:b62ff1818f2f69887eeaaae97099695c8774d2b1
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-njsscan-scanner -mode single

      - name: Gitleaks Scanner
        if: ${{ steps.plan.outputs.gitleaks == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-gitleaks-scanner:7ea235e34a162a35b4b03775e8dca2c773d1f7c3
        continue-on-error: true
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        run: /app/plugin-gitleaks-scanner -mode single

      - name: BlackDuck Scanner
        if: ${{ steps.plan.outputs.blackduck == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/plugin-blackduck-sca:415ec498524dd9e284ec24b012fe27496376d26a
        env:
          BLACKDUCK_PROPS : ${{ steps.plan.outputs.blackduck-props}}
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-blackduck-scanner -mode single

      - name: Coverity Polaris Scanner
        if: ${{ steps.plan.outputs.coverity == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/plugin-coverity-sca:df2e0193e1720f78db612cf13edb600150d1792f
        env:
          COVERITY_PROPS : ${{ steps.plan.outputs.coverity-props}}
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-coverity-polaris -mode single

      - name: Checkov Scanner
        if: ${{ steps.plan.outputs.checkov == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-checkov-scanner:28c61f52d97a97c79b07f1e0c5576af64e8ce3e8
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-checkov -mode single

      - name: Snyk SAST Scanner
        if: ${{ steps.plan.outputs.snykcode == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-snyk-sast-scanner:ce817b2ddbfc49b4b31888204347f567b642fde9
        env:
          SNYK_SAST_PROPS: ${{ steps.plan.outputs.snykcode-props}}
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-snyk-sast-scanner -mode single

      - name: Snyk IaC Scanner
        if: ${{ steps.plan.outputs.snyk-iac == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-snyk-iac-scanner:2bdcf9e581405f26f0314842e13192da0da6b123
        env:
          SNYK_IAC_PROPS: ${{ steps.plan.outputs.snyk-iac-props}}
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-snyk-iac-scanner -mode single

      - name: Snyk SCA Scanner
        if: ${{ steps.plan.outputs.snyksca == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-snyk-sca-scanner:80bea9113f19c64c9ff1d4c6a86c0519fbfebaab
        env:
          SNYK_SCA_PROPS: ${{ steps.plan.outputs.snyksca-props}}
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-snyk-sca-scanner -mode single

      - name: Perforce Klocwork Scanner
        if: ${{ steps.plan.outputs.perforce-klocwork-sast == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-klocwork-scanner:fdb53c7fd3c1e8c795c2796e7414edbada9b6113
        env:
          KLOCWORK_PROPS: ${{ steps.plan.outputs.perforce-klocwork-sast-props}}
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-klocwork-scanner -mode single


      - name: Sonar Scanner
        if: ${{ steps.plan.outputs.sonar == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-sonarqube-scanner:75d608d933dc16ac6c91272a9faec761cc67314c
        env:
          SONARQUBE_PROPS: ${{ steps.plan.outputs.sonar-props}}
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-sonarqube-scanner -mode single


      - name: Complete execution plan
        uses: https://github.com/cloudbees-io/asset-chain-utils/end-chain@v1
        id: process-outputs
