apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name:  scan

jobs:
  scan:
    steps:
      - name: Initiate execution plan
        uses: https://github.com/cloudbees-io/asset-chain-utils/start-chain@v1
        id: plan


      - name: Github Inventory
        if: ${{ steps.plan.outputs.github-inventory == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-github-inventory:e7444f9a1dad87482778356ec66dcd5f22e1e71e
        env:
          ACCOUNT_CREDENTIALS: ${{ steps.plan.outputs.account_credentials}}
        run: /app/plugin-git-master -mode single

      - name: Github Metadata
        if: ${{ steps.plan.outputs.github-decorator == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-github-metadata:532d1b6873dbbc40ab3e3726a8d929f8e4d02d99
        env:
          ACCOUNT_CREDENTIALS: ${{ steps.plan.outputs.account_credentials}}
        run: /app/plugin-git-decorator -mode single

      - name: Bitbucket Inventory
        if: ${{ steps.plan.outputs.bitbucket-inventory == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-bitbucket-server:eb81dba284f3a4fc1c5c60de0dd0c8946f8b4ae2
        env:
          ACCOUNT_CREDENTIALS: ${{ steps.plan.outputs.account_credentials}}
          EXECUTION_ROLE: "MASTER"
        run: /app/plugin-bitbucket -mode single

      - name: Bitbucket Metadata
        if: ${{ steps.plan.outputs.bitbucket-decorator == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-bitbucket-server:eb81dba284f3a4fc1c5c60de0dd0c8946f8b4ae2
        env:
          ACCOUNT_CREDENTIALS: ${{ steps.plan.outputs.account_credentials}}
          EXECUTION_ROLE: "DECORATOR"
        run: /app/plugin-bitbucket -mode single

      - name: SCC Scanner
        if: ${{ steps.plan.outputs.scc == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-scc-scanner:6c844d4427ec4ed03fdee4aec65a671cf840d6a4
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-scc-scanner -mode single

      - name: GoSec Scanner
        if: ${{ steps.plan.outputs.gosec == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-gosec-scanner:1b2c0980e5495cc0132a3e693ba8e6ebf2c7cd71
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-gosec-scanner -mode single

      - name: Njs Scanner
        if: ${{ steps.plan.outputs.njsscan == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-njsscan-scanner:b62ff1818f2f69887eeaaae97099695c8774d2b1
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-njsscan-scanner -mode single

      - name: Gitleaks Scanner
        if: ${{ steps.plan.outputs.gitleaks == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-gitleaks-scanner:7ea235e34a162a35b4b03775e8dca2c773d1f7c3
        continue-on-error: true
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        run: /app/plugin-gitleaks-scanner -mode single

      - name: BlackDuck Scanner
        if: ${{ steps.plan.outputs.blackduck == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/plugin-blackduck-sca:f0bf9cebb1b27fe54762c4fcb254697a255bcaec
        env:
          BLACKDUCK_PROPS : ${{ steps.plan.outputs.blackduck-props}}
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-blackduck-scanner -mode single

      - name: Coverity Polaris Scanner
        if: ${{ steps.plan.outputs.coverity == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/plugin-coverity-sca:df2e0193e1720f78db612cf13edb600150d1792f
        env:
          COVERITY_PROPS : ${{ steps.plan.outputs.coverity-props}}
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-coverity-polaris -mode single

      - name: Checkov Scanner
        if: ${{ steps.plan.outputs.checkov == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-checkov-scanner:f0108b3408abe89b095b0af3c9bf47b96ec6970b
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-checkov -mode single

      - name: Sonar Scanner
        if: ${{ steps.plan.outputs.sonar == 'true' }}
        uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-sonarqube-scanner:d22c15088ff7668499d80bc4d204966d9ca7d2d9
        env:
          SONARQUBE_PROPS: ${{ steps.plan.outputs.sonar-props}}
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-sonarqube-scanner -mode single


      - name: Complete execution plan
        uses: https://github.com/cloudbees-io/asset-chain-utils/end-chain@v1
        id: process-outputs
